name: Ejecutar Estudiantes ITM

on:
  push:
    branches:
      - main

jobs:
  ejecutar-main:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar el entorno
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip

    - name: Ejecutar script
      run: |
        python main.py
